# Generated by Django 5.0.2 on 2025-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='libelle_de_projet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Libellé de Projet'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resources/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rank',
            field=models.CharField(max_length=50, verbose_name='Rank'),
        ),
    ]
