# Generated by Django 5.0.2 on 2025-05-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_mission_libelle_de_projet_alter_resource_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='code_type',
            field=models.CharField(choices=[('FR', 'Code France'), ('DES', 'Code DES')], default='FR', max_length=3, verbose_name='Type de Code'),
        ),
    ]
