# Generated by Django 5.0.2 on 2025-05-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_mission_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='comment',
        ),
    ]
