# Generated by Django 5.0.2 on 2025-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_mission_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='rank',
        ),
        migrations.AddField(
            model_name='resource',
            name='grade',
            field=models.CharField(choices=[('FR_JSA', 'FR_Junior Staff / Analyst'), ('FR_MGR', 'FR_Manager'), ('FR_NEP', 'FR_Non Equity Partner'), ('FR_SMGR', 'FR_Senior Manager'), ('FR_SRS', 'FR_Senior Staff'), ('FR_STF', 'FR_Staff')], default='FR_STF', max_length=10, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='resource',
            name='grade_des',
            field=models.CharField(choices=[('DES_M3', 'Manager 3'), ('DES_M2', 'Manager 2'), ('DES_M1', 'Manager 1'), ('DES_SC3', 'Senior Consultant 3'), ('DES_SC2', 'Senior Consultant 2'), ('DES_SC1', 'Senior Consultant 1'), ('DES_C2', 'Consultant 2'), ('DES_CJ', 'Consultant Junior'), ('DES_STG', 'Stagiaire')], default='DES_STG', max_length=10, verbose_name='Grade DES'),
        ),
    ]
