# Generated by Django 5.0.2 on 2025-05-24 19:47

from django.db import migrations

def swap_data_forward(apps, schema_editor):
    Mission = apps.get_model('billing', 'Mission')
    for mission in Mission.objects.all():
        # Store one value in a temporary variable
        temp_belgian_name_data = mission.belgian_name
        # Move libelle_de_projet's data into belgian_name field
        mission.belgian_name = mission.libelle_de_projet
        # Move original belgian_name's data (stored in temp) into libelle_de_projet field
        mission.libelle_de_projet = temp_belgian_name_data
        mission.save(update_fields=['belgian_name', 'libelle_de_projet'])

def swap_data_backward(apps, schema_editor):
    # The reverse operation is the same swap
    Mission = apps.get_model('billing', 'Mission')
    for mission in Mission.objects.all():
        temp_belgian_name_data = mission.belgian_name
        mission.belgian_name = mission.libelle_de_projet
        mission.libelle_de_projet = temp_belgian_name_data
        mission.save(update_fields=['belgian_name', 'libelle_de_projet'])

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_resource_grade_des'),
    ]

    operations = [
        migrations.RunPython(swap_data_forward, swap_data_backward),
    ]
