# Generated by Django 5.0.2 on 2025-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_update_mission_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='calculated_estimee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimée Calculée'),
        ),
        migrations.AddField(
            model_name='mission',
            name='calculated_total_heures',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Heures Calculées'),
        ),
        migrations.AddField(
            model_name='mission',
            name='calculation_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Période de Calcul'),
        ),
    ]
