# Generated by Django 5.0.2 on 2025-05-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_mission_calculation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='grade_des',
            field=models.CharField(choices=[('DES_M3', 'Manager 3'), ('DES_M2', 'Manager 2'), ('DES_M1', 'Manager 1'), ('DES_SC3', 'Senior Consultant 3'), ('DES_SC2', 'Senior Consultant 2'), ('DES_SC1', 'Senior Consultant 1'), ('DES_C2', 'Consultant 2'), ('DES_C1', 'Consultant 1'), ('DES_CJ', 'Consultant Junior'), ('DES_STG', 'Stagiaire'), ('DES_NA', 'N/A')], default='DES_STG', max_length=10, verbose_name='Grade DES'),
        ),
    ]
