# Generated by Django 5.0.2 on 2025-05-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_consultant_1_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='grade',
            field=models.CharField(choices=[('FR_JSA', 'FR_Junior Staff / Analyst'), ('FR_MGR', 'FR_Manager'), ('FR_NEP', 'FR_Non Equity Partner'), ('FR_SMGR', 'FR_Senior Manager'), ('FR_SRS', 'FR_Senior Staff'), ('FR_STF', 'FR_Staff'), ('FR_STG', 'FR_Stagiaire / Alternants')], default='FR_STF', max_length=10, verbose_name='Grade'),
        ),
    ]
